/** Mart rows as the Phase 1d API returns them (values from the live database, 2026-09-12). */
import type {
  CommitteeAssignment,
  FeedItem,
  KeyDate,
  MemberDetail,
  MemberListItem,
  WeekBucket,
} from '@/lib/types';

export const STEIL: MemberDetail = {
  bioguide_id: 'S001213',
  name: { first: 'Bryan', last: 'Steil', official_full: 'Bryan Steil' },
  party: 'Republican',
  seat: {
    chamber: 'house',
    state: 'WI',
    state_name: 'Wisconsin',
    fips_state: '55',
    district: 1,
    senate_class: null,
    state_rank: null,
    label: 'WI-1',
  },
  term: {
    congress: 119,
    end_congress: 119,
    congresses: [119],
    tracked_congress: 119,
    start_date: '2025-01-03',
    end_date: '2027-01-03',
    days_remaining: 112,
    days_elapsed: 618,
  },
  photo_url: 'https://www.congress.gov/img/member/s001213_200.jpg',
  votes: {
    roll_calls: 657,
    positions: 657,
    votes_cast: 652,
    not_voting: 5,
    attendance_pct: 99.24,
    missed_vote_pct: 0.76,
    party_unity_pct: 98.61,
    party_unity_cq_pct: 98.7,
  },
  activity: { bills_sponsored: 36, bills_cosponsored: 118, committees: 6, chairmanships: 2 },
  sources: [],
};

export const COTTON: MemberDetail = {
  bioguide_id: 'C001095',
  name: { first: 'Tom', last: 'Cotton', official_full: 'Tom Cotton' },
  party: 'Republican',
  seat: {
    chamber: 'senate',
    state: 'AR',
    state_name: 'Arkansas',
    fips_state: '05',
    district: null,
    senate_class: 2,
    state_rank: 'junior',
    label: 'Arkansas (Class 2)',
  },
  term: {
    congress: 117,
    end_congress: 119,
    congresses: [117, 118, 119],
    tracked_congress: 119,
    start_date: '2021-01-03',
    end_date: '2027-01-03',
    days_remaining: 112,
    days_elapsed: 2079,
  },
  photo_url: null,
  votes: {
    roll_calls: 890,
    positions: 890,
    votes_cast: 876,
    not_voting: 14,
    attendance_pct: 98.43,
    missed_vote_pct: 1.57,
    party_unity_pct: 99.77,
    party_unity_cq_pct: 99.75,
  },
  activity: { bills_sponsored: 111, bills_cosponsored: 206, committees: 10, chairmanships: 1 },
  sources: [],
};

export const STEIL_LIST: MemberListItem = {
  bioguide_id: 'S001213',
  name: STEIL.name,
  party: 'Republican',
  seat: STEIL.seat,
  photo_url: STEIL.photo_url,
};

export const COTTON_LIST: MemberListItem = {
  bioguide_id: 'C001095',
  name: COTTON.name,
  party: 'Republican',
  seat: COTTON.seat,
  photo_url: null,
};

export const STEIL_COMMITTEES: CommitteeAssignment[] = [
  { thomas_id: 'HSBA', name: 'House Committee on Financial Services', chamber: 'house', parent_thomas_id: null, parent_name: null, rank: 12, title: null },
  { thomas_id: 'HSBA16', name: 'Capital Markets', chamber: 'house', parent_thomas_id: 'HSBA', parent_name: 'House Committee on Financial Services', rank: 6, title: null },
  { thomas_id: 'HSBA21', name: 'Digital Assets, Financial Technology, and Artificial Intelligence', chamber: 'house', parent_thomas_id: 'HSBA', parent_name: 'House Committee on Financial Services', rank: 1, title: 'Chairman' },
  { thomas_id: 'HSHA', name: 'House Committee on House Administration', chamber: 'house', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Chair' },
  { thomas_id: 'JSLC', name: 'Joint Committee of Congress on the Library', chamber: 'joint', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Chair' },
  { thomas_id: 'JSPR', name: 'Joint Committee on Printing', chamber: 'joint', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Vice Chair' },
];

export const STEIL_KEY_DATES: KeyDate[] = [
  { date: '2025-01-03', label: '119th Congress convenes', kind: 'session', scope: 'congress', scope_value: null, note: null, source_url: 'https://constitution.congress.gov/constitution/amendment-20/' },
  { date: '2026-06-01', label: 'Wisconsin nomination papers due by 5 p.m.', kind: 'deadline', scope: 'state', scope_value: 'WI', note: null, source_url: 'https://docs.legis.wisconsin.gov/statutes/statutes/8/15' },
  { date: '2026-08-11', label: 'Wisconsin partisan primary', kind: 'election', scope: 'state', scope_value: 'WI', note: null, source_url: 'https://docs.legis.wisconsin.gov/statutes/statutes/5/02' },
  { date: '2026-11-03', label: 'General election day', kind: 'election', scope: 'congress', scope_value: null, note: null, source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title2-section7' },
  { date: '2027-01-03', label: '119th Congress ends; House and Class 2 Senate terms expire at noon', kind: 'session', scope: 'congress', scope_value: null, note: null, source_url: 'https://constitution.congress.gov/constitution/amendment-20/' },
];

export const FEED: FeedItem[] = [
  {
    event_key: 'vote:house:2:295',
    event_type: 'vote',
    event_at: '2026-09-03T18:24:00Z',
    event_date: '2026-09-03',
    headline: 'Voted YEA on H.R. 4795: Protect Economic and Academic Freedom Act of 2026',
    detail: 'On Passage · Passed 237–169',
    detail_full: null,
    position: 'Yea',
    chamber: 'house',
    session: 2,
    roll_number: 295,
    bill_type: 'hr',
    bill_number: '4795',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/4795',
    source_url: 'https://clerk.house.gov/evs/2026/roll295.xml',
  },
  {
    event_key: 'vote:senate:2:1',
    event_type: 'vote',
    event_at: '2026-01-05T22:31:00Z',
    event_date: '2026-01-05',
    headline: 'Voted YEA on nomination PN12-1',
    detail: 'On the Nomination · Nomination Confirmed 52–45',
    detail_full: null,
    position: 'Yea',
    chamber: 'senate',
    session: 2,
    roll_number: 1,
    bill_type: null,
    bill_number: null,
    url: null,
    source_url: 'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1192/vote_119_2_00001.xml',
  },
  {
    event_key: 'vote:house:1:353',
    event_type: 'vote',
    event_at: '2025-12-17T20:00:00Z',
    event_date: '2025-12-17',
    headline: 'Did not vote on roll call 353',
    detail: 'On Agreeing to the Amendment · Failed 201–224',
    detail_full: null,
    position: 'Not Voting',
    chamber: 'house',
    session: 1,
    roll_number: 353,
    bill_type: null,
    bill_number: null,
    url: null,
    source_url: 'https://clerk.house.gov/evs/2025/roll353.xml',
  },
  {
    event_key: 'vote:house:1:2',
    event_type: 'vote',
    event_at: '2025-01-03T18:00:00Z',
    event_date: '2025-01-03',
    headline: 'Voted Johnson (LA) on roll call 2',
    detail: 'Election of the Speaker · Passed 0–0',
    detail_full: null,
    position: 'Other',
    chamber: 'house',
    session: 1,
    roll_number: 2,
    bill_type: null,
    bill_number: null,
    url: null,
    source_url: 'https://clerk.house.gov/evs/2025/roll002.xml',
  },
  {
    event_key: 'bill_sponsor:119:hr:4735',
    event_type: 'bill_sponsored',
    event_at: '2025-07-23T04:00:00Z',
    event_date: '2025-07-23',
    headline: 'Introduced H.R. 4735: Business of Insurance Regulatory Reform Act of 2025',
    detail: 'Referred to the House Committee on Financial Services.',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hr',
    bill_number: '4735',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/4735',
    source_url: 'https://api.congress.gov/v3/member/S001213/sponsored-legislation?format=json',
  },
  {
    event_key: 'bill_cosponsor:119:hr:5269',
    event_type: 'bill_cosponsored',
    event_at: '2026-09-04T04:00:00Z',
    event_date: '2026-09-04',
    headline: 'Cosponsored H.R. 5269: RESULTS Act',
    detail: 'Referred to the Committee on Energy and Commerce.',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hr',
    bill_number: '5269',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/5269',
    source_url: 'https://api.congress.gov/v3/member/S001213/cosponsored-legislation?format=json',
  },
  {
    event_key: 'action:119:hres:150:2025-02-21:abc',
    event_type: 'committee_action',
    event_at: '2025-02-21T17:00:00Z',
    event_date: '2025-02-21',
    headline: 'H.Res. 150: Submitted in House',
    detail: 'Providing for consideration of the bill',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hres',
    bill_number: '150',
    url: 'https://www.congress.gov/bill/119th-congress/house-resolution/150',
    source_url: 'https://api.congress.gov/v3/bill/119/hres/150/actions?format=json',
  },
];

export const EN_BLOC: FeedItem = {
  event_key: 'vote:senate:1:522',
  event_type: 'vote',
  event_at: '2025-10-07T21:12:00Z',
  event_date: '2025-10-07',
  headline: 'Voted YEA on 48 nominations (en bloc)',
  detail: 'On the Cloture Motion · 48 nominations · Cloture Motion Rejected 51–48',
  detail_full: 'On the Cloture Motion PN25-28 and PN12-19 and PN12-45 and PN22-1 · Cloture Motion Rejected 51–48',
  position: 'Yea',
  chamber: 'senate',
  session: 1,
  roll_number: 522,
  bill_type: null,
  bill_number: null,
  url: null,
  source_url: 'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00522.xml',
};

export const WEEKS: WeekBucket[] = [
  { week_start: '2025-07-21', vote: 12, bill_sponsored: 1, bill_cosponsored: 3, committee_action: 0, total: 16 },
  { week_start: '2026-08-31', vote: 9, bill_sponsored: 0, bill_cosponsored: 2, committee_action: 1, total: 12 },
];
