/** Mart rows as the Phase 1d API returns them (values from the live database, 2026-09-12). */
import type {
  BillDetail,
  CommitteeAssignment,
  CongressSession,
  FeedItem,
  FundraisingResponse,
  KeyDate,
  MemberDetail,
  MemberIds,
  MemberListItem,
  TermHistoryItem,
  WeekBucket,
} from '@/lib/types';

const NO_IDS: MemberIds = {
  govtrack: null,
  icpsr: null,
  fec: [],
  lis: null,
  opensecrets: null,
  wikipedia: null,
  ballotpedia: null,
  cspan: null,
  votesmart: null,
  wikidata: null,
};

/** mart.term_history rows: one House term. */
function houseTerm(
  index: number,
  congress: number,
  start: string,
  end: string,
  state: string,
  district: number,
  party: string,
): TermHistoryItem {
  return {
    term_index: index,
    chamber: 'house',
    congress,
    end_congress: congress,
    start_date: start,
    end_date: end,
    state,
    district,
    senate_class: null,
    party,
    caucus: null,
    how: null,
    end_type: null,
  };
}

function senateTerm(
  index: number,
  congress: number,
  endCongress: number,
  start: string,
  end: string,
  state: string,
  senateClass: number,
  party: string,
  caucus: string | null = null,
): TermHistoryItem {
  return {
    term_index: index,
    chamber: 'senate',
    congress,
    end_congress: endCongress,
    start_date: start,
    end_date: end,
    state,
    district: null,
    senate_class: senateClass,
    party,
    caucus,
    how: null,
    end_type: null,
  };
}

export const STEIL: MemberDetail = {
  bioguide_id: 'S001213',
  name: { first: 'Bryan', last: 'Steil', official_full: 'Bryan Steil' },
  party: 'Republican',
  caucus: null,
  seat: {
    chamber: 'house',
    state: 'WI',
    state_name: 'Wisconsin',
    fips_state: '55',
    district: 1,
    senate_class: null,
    state_rank: null,
    label: 'WI-1',
  },
  term: {
    congress: 119,
    end_congress: 119,
    congresses: [119],
    tracked_congress: 119,
    start_date: '2025-01-03',
    end_date: '2027-01-03',
    days_remaining: 112,
    days_elapsed: 618,
  },
  bio: { birthday: '1981-03-30', age: 45, gender: 'M' },
  service: {
    first_term_start: '2019-01-03',
    serving_since: '2019-01-03',
    term_number: 4,
    chamber_since: '2019-01-03',
    chamber_term_number: 4,
    terms: [
      houseTerm(1, 116, '2019-01-03', '2021-01-03', 'WI', 1, 'Republican'),
      houseTerm(2, 117, '2021-01-03', '2023-01-03', 'WI', 1, 'Republican'),
      houseTerm(3, 118, '2023-01-03', '2025-01-03', 'WI', 1, 'Republican'),
      houseTerm(4, 119, '2025-01-03', '2027-01-03', 'WI', 1, 'Republican'),
    ],
  },
  leadership: [],
  photo_url: 'https://www.congress.gov/img/member/s001213_200.jpg',
  ids: { ...NO_IDS, govtrack: 412836, icpsr: 21970, fec: ['H8WI01156'], opensecrets: 'N00043379', wikipedia: 'Bryan Steil', ballotpedia: 'Bryan Steil', votesmart: 181289, wikidata: 'Q58494431' },
  votes: {
    roll_calls: 657,
    positions: 657,
    votes_cast: 652,
    not_voting: 5,
    attendance_pct: 99.24,
    missed_vote_pct: 0.76,
    scoring_party: 'R',
    party_unity_pct: 98.61,
    party_unity_cq_pct: 98.7,
  },
  activity: { bills_sponsored: 36, bills_cosponsored: 118, committees: 6, chairmanships: 2 },
  sources: [],
};

export const COTTON: MemberDetail = {
  bioguide_id: 'C001095',
  name: { first: 'Tom', last: 'Cotton', official_full: 'Tom Cotton' },
  party: 'Republican',
  caucus: null,
  seat: {
    chamber: 'senate',
    state: 'AR',
    state_name: 'Arkansas',
    fips_state: '05',
    district: null,
    senate_class: 2,
    state_rank: 'junior',
    label: 'Arkansas (Class 2)',
  },
  term: {
    congress: 117,
    end_congress: 119,
    congresses: [117, 118, 119],
    tracked_congress: 119,
    start_date: '2021-01-03',
    end_date: '2027-01-03',
    days_remaining: 112,
    days_elapsed: 2079,
  },
  bio: { birthday: '1977-05-13', age: 49, gender: 'M' },
  // House 2013-2015, then the Senate from 2015-01-06: continuous service since 2013
  service: {
    first_term_start: '2013-01-03',
    serving_since: '2013-01-03',
    term_number: 3,
    chamber_since: '2015-01-06',
    chamber_term_number: 2,
    terms: [
      houseTerm(1, 113, '2013-01-03', '2015-01-03', 'AR', 4, 'Republican'),
      senateTerm(2, 114, 116, '2015-01-06', '2021-01-03', 'AR', 2, 'Republican'),
      senateTerm(3, 117, 119, '2021-01-03', '2027-01-03', 'AR', 2, 'Republican'),
    ],
  },
  leadership: [
    { title: 'Senate Republican Conference Chair', chamber: 'senate', start_date: '2025-01-03', end_date: null, is_current: true },
  ],
  photo_url: null,
  ids: { ...NO_IDS, govtrack: 412508, icpsr: 21301, lis: 'S374', fec: ['H2AR04083', 'S4AR00103'], opensecrets: 'N00033363', wikipedia: 'Tom Cotton', ballotpedia: 'Tom Cotton', cspan: 63928, votesmart: 135651, wikidata: 'Q3090307' },
  votes: {
    roll_calls: 890,
    positions: 890,
    votes_cast: 876,
    not_voting: 14,
    attendance_pct: 98.43,
    missed_vote_pct: 1.57,
    scoring_party: 'R',
    party_unity_pct: 99.77,
    party_unity_cq_pct: 99.75,
  },
  activity: { bills_sponsored: 111, bills_cosponsored: 206, committees: 10, chairmanships: 1 },
  sources: [],
};

/** Independent who caucuses with the Democrats; 12th term, 4th in the Senate (mart, 2026-09-13). */
export const SANDERS: MemberDetail = {
  bioguide_id: 'S000033',
  name: { first: 'Bernard', middle: null, last: 'Sanders', nickname: 'Bernie', suffix: null, official_full: 'Bernard Sanders' },
  party: 'Independent',
  caucus: 'Democrat',
  seat: {
    chamber: 'senate',
    state: 'VT',
    state_name: 'Vermont',
    fips_state: '50',
    district: null,
    senate_class: 1,
    state_rank: 'senior',
    label: 'Vermont (Class 1)',
  },
  term: {
    congress: 119,
    end_congress: 121,
    congresses: [119, 120, 121],
    tracked_congress: 119,
    start_date: '2025-01-03',
    end_date: '2031-01-03',
    days_remaining: 1573,
    days_elapsed: 618,
  },
  bio: { birthday: '1941-09-08', age: 85, gender: 'M' },
  service: {
    first_term_start: '1991-01-03',
    serving_since: '1991-01-03',
    term_number: 12,
    chamber_since: '2007-01-04',
    chamber_term_number: 4,
    terms: [
      houseTerm(1, 102, '1991-01-03', '1993-01-03', 'VT', 0, 'Independent'),
      houseTerm(8, 109, '2005-01-04', '2007-01-03', 'VT', 0, 'Independent'),
      senateTerm(9, 110, 112, '2007-01-04', '2013-01-03', 'VT', 1, 'Independent'),
      senateTerm(12, 119, 121, '2025-01-03', '2031-01-03', 'VT', 1, 'Independent', 'Democrat'),
    ],
  },
  leadership: [
    { title: 'Senate Democratic Outreach Chair', chamber: 'senate', start_date: '2025-01-03', end_date: null, is_current: true },
    { title: 'Senate Democratic Outreach Chair', chamber: 'senate', start_date: '2023-01-03', end_date: '2025-01-03', is_current: false },
  ],
  photo_url: 'https://www.congress.gov/img/member/s000033_200.jpg',
  ids: { ...NO_IDS, govtrack: 400357, icpsr: 29147, lis: 'S313', fec: ['H8VT01016', 'S4VT00033'], opensecrets: 'N00000528', wikipedia: 'Bernie Sanders', ballotpedia: 'Bernie Sanders', cspan: 994, votesmart: 27110, wikidata: 'Q359442' },
  votes: {
    roll_calls: 890,
    positions: 887,
    votes_cast: 824,
    not_voting: 63,
    attendance_pct: 92.9,
    missed_vote_pct: 7.1,
    scoring_party: 'D',
    party_unity_pct: 95.26,
    party_unity_cq_pct: 99.87,
  },
  activity: { bills_sponsored: 40, bills_cosponsored: 200, committees: 14, chairmanships: 0 },
  sources: [],
};

/** First-term senator with three House terms behind her. */
export const SLOTKIN: MemberDetail = {
  ...SANDERS,
  bioguide_id: 'S001208',
  name: { first: 'Elissa', middle: null, last: 'Slotkin', nickname: null, suffix: null, official_full: 'Elissa Slotkin' },
  party: 'Democrat',
  caucus: null,
  seat: { ...SANDERS.seat, state: 'MI', state_name: 'Michigan', fips_state: '26', state_rank: 'junior', label: 'Michigan (Class 1)' },
  bio: { birthday: '1976-07-10', age: 50, gender: 'F' },
  service: {
    first_term_start: '2019-01-03',
    serving_since: '2019-01-03',
    term_number: 4,
    chamber_since: '2025-01-03',
    chamber_term_number: 1,
    terms: [
      houseTerm(1, 116, '2019-01-03', '2021-01-03', 'MI', 8, 'Democrat'),
      houseTerm(2, 117, '2021-01-03', '2023-01-03', 'MI', 8, 'Democrat'),
      houseTerm(3, 118, '2023-01-03', '2025-01-03', 'MI', 7, 'Democrat'),
      senateTerm(4, 119, 121, '2025-01-03', '2031-01-03', 'MI', 1, 'Democrat'),
    ],
  },
  leadership: [],
  photo_url: null,
  ids: { ...NO_IDS, lis: 'S436' },
  votes: { ...SANDERS.votes, votes_cast: 862, not_voting: 25, attendance_pct: 97.18, missed_vote_pct: 2.82, party_unity_pct: 92.57, party_unity_cq_pct: 92.24 },
  activity: { bills_sponsored: 30, bills_cosponsored: 150, committees: 11, chairmanships: 0 },
};

export const STEIL_LIST: MemberListItem = {
  bioguide_id: 'S001213',
  name: STEIL.name,
  party: 'Republican',
  caucus: null,
  seat: STEIL.seat,
  photo_url: STEIL.photo_url,
};

export const COTTON_LIST: MemberListItem = {
  bioguide_id: 'C001095',
  name: COTTON.name,
  party: 'Republican',
  caucus: null,
  seat: COTTON.seat,
  photo_url: null,
};

export const SANDERS_LIST: MemberListItem = {
  bioguide_id: 'S000033',
  name: SANDERS.name,
  party: 'Independent',
  caucus: 'Democrat',
  seat: SANDERS.seat,
  photo_url: SANDERS.photo_url,
};

export const SLOTKIN_LIST: MemberListItem = {
  bioguide_id: 'S001208',
  name: SLOTKIN.name,
  party: 'Democrat',
  caucus: null,
  seat: SLOTKIN.seat,
  photo_url: null,
};

export const STEIL_COMMITTEES: CommitteeAssignment[] = [
  { thomas_id: 'HSBA', name: 'House Committee on Financial Services', chamber: 'house', parent_thomas_id: null, parent_name: null, rank: 12, title: null },
  { thomas_id: 'HSBA16', name: 'Capital Markets', chamber: 'house', parent_thomas_id: 'HSBA', parent_name: 'House Committee on Financial Services', rank: 6, title: null },
  { thomas_id: 'HSBA21', name: 'Digital Assets, Financial Technology, and Artificial Intelligence', chamber: 'house', parent_thomas_id: 'HSBA', parent_name: 'House Committee on Financial Services', rank: 1, title: 'Chairman' },
  { thomas_id: 'HSHA', name: 'House Committee on House Administration', chamber: 'house', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Chair' },
  { thomas_id: 'JSLC', name: 'Joint Committee of Congress on the Library', chamber: 'joint', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Chair' },
  { thomas_id: 'JSPR', name: 'Joint Committee on Printing', chamber: 'joint', parent_thomas_id: null, parent_name: null, rank: 1, title: 'Vice Chair' },
];

export const STEIL_KEY_DATES: KeyDate[] = [
  { date: '2025-01-03', label: '119th Congress convenes', kind: 'session', scope: 'congress', scope_value: null, note: null, source_url: 'https://constitution.congress.gov/constitution/amendment-20/' },
  { date: '2026-06-01', label: 'Wisconsin nomination papers due by 5 p.m.', kind: 'deadline', scope: 'state', scope_value: 'WI', note: null, source_url: 'https://docs.legis.wisconsin.gov/statutes/statutes/8/15' },
  { date: '2026-08-11', label: 'Wisconsin partisan primary', kind: 'election', scope: 'state', scope_value: 'WI', note: null, source_url: 'https://docs.legis.wisconsin.gov/statutes/statutes/5/02' },
  { date: '2026-11-03', label: 'General election day', kind: 'election', scope: 'congress', scope_value: null, note: null, source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title2-section7' },
  { date: '2027-01-03', label: '119th Congress ends; House and Class 2 Senate terms expire at noon', kind: 'session', scope: 'congress', scope_value: null, note: null, source_url: 'https://constitution.congress.gov/constitution/amendment-20/' },
];

export const FEED: FeedItem[] = [
  {
    event_key: 'vote:house:2:295',
    event_type: 'vote',
    congress: 119,
    event_at: '2026-09-03T18:24:00Z',
    event_date: '2026-09-03',
    headline: 'Voted YEA on H.R. 4795: Protect Economic and Academic Freedom Act of 2026',
    detail: 'On Passage · Passed 237–169',
    detail_full: null,
    position: 'Yea',
    chamber: 'house',
    session: 2,
    roll_number: 295,
    bill_type: 'hr',
    bill_number: '4795',
    bill_label: 'H.R. 4795',
    policy_area: 'Education',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/4795',
    source_url: 'https://clerk.house.gov/evs/2026/roll295.xml',
  },
  {
    event_key: 'vote:senate:2:1',
    event_type: 'vote',
    congress: 119,
    event_at: '2026-01-05T22:31:00Z',
    event_date: '2026-01-05',
    headline: 'Voted YEA on nomination PN12-1',
    detail: 'On the Nomination · Nomination Confirmed 52–45',
    detail_full: null,
    position: 'Yea',
    chamber: 'senate',
    session: 2,
    roll_number: 1,
    bill_type: null,
    bill_number: null,
    bill_label: null,
  policy_area: null,
    url: null,
    source_url: 'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1192/vote_119_2_00001.xml',
  },
  {
    event_key: 'vote:house:1:353',
    event_type: 'vote',
    congress: 119,
    event_at: '2025-12-17T20:00:00Z',
    event_date: '2025-12-17',
    headline: 'Did not vote on roll call 353',
    detail: 'On Agreeing to the Amendment · Failed 201–224',
    detail_full: null,
    position: 'Not Voting',
    chamber: 'house',
    session: 1,
    roll_number: 353,
    bill_type: null,
    bill_number: null,
    bill_label: null,
  policy_area: null,
    url: null,
    source_url: 'https://clerk.house.gov/evs/2025/roll353.xml',
  },
  {
    event_key: 'vote:house:1:2',
    event_type: 'vote',
    congress: 119,
    event_at: '2025-01-03T18:00:00Z',
    event_date: '2025-01-03',
    headline: 'Voted Johnson (LA) on roll call 2',
    detail: 'Election of the Speaker · Passed 0–0',
    detail_full: null,
    position: 'Other',
    chamber: 'house',
    session: 1,
    roll_number: 2,
    bill_type: null,
    bill_number: null,
    bill_label: null,
  policy_area: null,
    url: null,
    source_url: 'https://clerk.house.gov/evs/2025/roll002.xml',
  },
  {
    event_key: 'bill_sponsor:119:hr:4735',
    event_type: 'bill_sponsored',
    congress: 119,
    event_at: '2025-07-23T04:00:00Z',
    event_date: '2025-07-23',
    headline: 'Introduced H.R. 4735: Business of Insurance Regulatory Reform Act of 2025',
    detail: 'Referred to the House Committee on Financial Services.',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hr',
    bill_number: '4735',
    bill_label: 'H.R. 4735',
    policy_area: 'Finance and Financial Sector',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/4735',
    source_url: 'https://api.congress.gov/v3/member/S001213/sponsored-legislation?format=json',
  },
  {
    event_key: 'bill_cosponsor:119:hr:5269',
    event_type: 'bill_cosponsored',
    congress: 119,
    event_at: '2026-09-04T04:00:00Z',
    event_date: '2026-09-04',
    headline: 'Cosponsored H.R. 5269: RESULTS Act',
    detail: 'Referred to the Committee on Energy and Commerce.',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hr',
    bill_number: '5269',
    bill_label: 'H.R. 5269',
    policy_area: 'Government Operations and Politics',
    url: 'https://www.congress.gov/bill/119th-congress/house-bill/5269',
    source_url: 'https://api.congress.gov/v3/member/S001213/cosponsored-legislation?format=json',
  },
  {
    event_key: 'action:119:hres:150:2025-02-21:abc',
    event_type: 'committee_action',
    congress: 119,
    event_at: '2025-02-21T17:00:00Z',
    event_date: '2025-02-21',
    headline: 'H.Res. 150: Submitted in House',
    detail: 'Providing for consideration of the bill',
    detail_full: null,
    position: null,
    chamber: null,
    session: null,
    roll_number: null,
    bill_type: 'hres',
    bill_number: '150',
    bill_label: 'H.Res. 150',
    policy_area: 'Congress',
    url: 'https://www.congress.gov/bill/119th-congress/house-resolution/150',
    source_url: 'https://api.congress.gov/v3/bill/119/hres/150/actions?format=json',
  },
];

export const EN_BLOC: FeedItem = {
  event_key: 'vote:senate:1:522',
  event_type: 'vote',
  congress: 119,
  event_at: '2025-10-07T21:12:00Z',
  event_date: '2025-10-07',
  headline: 'Voted YEA on 48 nominations (en bloc)',
  detail: 'On the Cloture Motion · 48 nominations · Cloture Motion Rejected 51–48',
  detail_full: 'On the Cloture Motion PN25-28 and PN12-19 and PN12-45 and PN22-1 · Cloture Motion Rejected 51–48',
  position: 'Yea',
  chamber: 'senate',
  session: 1,
  roll_number: 522,
  bill_type: null,
  bill_number: null,
  bill_label: null,
  policy_area: null,
  url: null,
  source_url: 'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00522.xml',
};

export const WEEKS: WeekBucket[] = [
  { week_start: '2025-07-21', vote: 12, bill_sponsored: 1, bill_cosponsored: 3, committee_action: 0, total: 16 },
  { week_start: '2026-08-31', vote: 9, bill_sponsored: 0, bill_cosponsored: 2, committee_action: 1, total: 12 },
];

/** mart.member_fundraising row for Steil as the API returned it on 2026-09-13. */
export const STEIL_FUNDRAISING: FundraisingResponse = {
  bioguide_id: 'S001213',
  cycle: 2026,
  status: 'filed',
  candidate: {
    candidate_id: 'H8WI01156',
    name: 'STEIL, BRYAN GEORGE',
    fec_url: 'https://www.fec.gov/data/candidate/H8WI01156/?cycle=2026&election_full=false',
  },
  committee: {
    committee_id: 'C00677286',
    name: 'STEIL FOR WISCONSIN, INC.',
    fec_url: 'https://www.fec.gov/data/committee/C00677286/?cycle=2026',
  },
  coverage: { start_date: '2025-01-01', end_date: '2026-07-22', last_report_type: 'PRE-PRIMARY', last_report_year: 2026 },
  totals: { raised: 5467777.07, spent: 1359848.79, cash_on_hand: 6327098.65, debts: 0 },
  receipts: {
    individual_small: { amount: 253362.51, pct: 4.63 },
    individual_large: { amount: 1240060.26, pct: 22.68 },
    individual: { amount: 1493422.77, pct: 27.31 },
    pac: { amount: 1633675.16, pct: 29.88 },
    party: { amount: 1000, pct: 0.02 },
    self_funding: { amount: 0, pct: 0 },
    transfers: { amount: 2190887.63, pct: 40.07 },
    other: { amount: 148791.51, pct: 2.72 },
  },
  small_donor_pct: 4.63,
  small_donor_of_individual_pct: 16.97,
  sources: [],
};

/** Cotton: the Senate committee (not the old House one), with debts outstanding. */
export const COTTON_FUNDRAISING: FundraisingResponse = {
  ...STEIL_FUNDRAISING,
  bioguide_id: 'C001095',
  candidate: {
    candidate_id: 'S4AR00103',
    name: 'COTTON, THOMAS',
    fec_url: 'https://www.fec.gov/data/candidate/S4AR00103/?cycle=2026&election_full=false',
  },
  committee: {
    committee_id: 'C00499988',
    name: 'COTTON FOR SENATE, INC.',
    fec_url: 'https://www.fec.gov/data/committee/C00499988/?cycle=2026',
  },
  coverage: { start_date: '2025-01-01', end_date: '2026-06-30', last_report_type: 'JULY QUARTERLY', last_report_year: 2026 },
  totals: { raised: 6233116.56, spent: 3752101.46, cash_on_hand: 9931884.93, debts: 73959 },
  receipts: {
    individual_small: { amount: 552196.55, pct: 8.86 },
    individual_large: { amount: 2621967.92, pct: 42.07 },
    individual: { amount: 3174164.47, pct: 50.92 },
    pac: { amount: 1129500, pct: 18.12 },
    party: { amount: 62000, pct: 0.99 },
    self_funding: { amount: 0, pct: 0 },
    transfers: { amount: 1373299.48, pct: 22.03 },
    other: { amount: 494152.61, pct: 7.93 },
  },
  small_donor_pct: 8.86,
  small_donor_of_individual_pct: 17.4,
};

export const NO_FILINGS_FUNDRAISING: FundraisingResponse = {
  ...STEIL_FUNDRAISING,
  status: 'no_filings',
  coverage: null,
  totals: null,
  receipts: null,
  small_donor_pct: null,
  small_donor_of_individual_pct: null,
};

export const NO_COMMITTEE_FUNDRAISING: FundraisingResponse = {
  ...NO_FILINGS_FUNDRAISING,
  status: 'no_committee',
  committee: null,
};

export const NO_CANDIDATE_FUNDRAISING: FundraisingResponse = {
  ...NO_COMMITTEE_FUNDRAISING,
  status: 'no_candidate',
  candidate: null,
};

/** GET /bills/119/hr/5269 as the API returns it, trimmed to what the page renders. */
export const BILL: BillDetail = {
  congress: 119,
  bill_type: 'hr',
  bill_number: '5269',
  label: 'H.R. 5269',
  kind: 'bill',
  title: 'RESULTS Act',
  policy_area: 'Government Operations and Politics',
  introduced_date: '2025-09-10',
  latest_action_date: '2025-09-11',
  latest_action_text: 'Referred to the Committee on Energy and Commerce.',
  sponsor: {
    bioguide_id: 'B001230',
    name: 'Tammy Baldwin',
    full_name: 'Rep. Baldwin, Tammy [D-WI-2]',
    party: 'D',
    state: 'WI',
    district: 2,
    is_tracked: false,
  },
  cosponsors: { total: 3, democratic: 1, republican: 2, other: 0, withdrawn: 1 },
  action_count: 3,
  summary_count: 2,
  has_summary: true,
  roll_call_count: 1,
  congress_gov_url: 'https://www.congress.gov/bill/119th-congress/house-bill/5269',
  amended_bill_congress: null,
  amended_bill_type: null,
  amended_bill_number: null,
  update_date: '2026-09-04T00:00:00Z',
  summary: {
    version_code: '53',
    action_date: '2026-01-14',
    action_desc: 'Passed House',
    text_html:
      '<p><strong>RESULTS Act</strong></p><p>This bill requires agencies to publish outcomes.</p>',
    text_length: 96,
    update_date: '2026-01-20T10:00:00Z',
    is_latest: true,
  },
  summary_versions: [
    {
      version_code: '53',
      action_date: '2026-01-14',
      action_desc: 'Passed House',
      text_html:
        '<p><strong>RESULTS Act</strong></p><p>This bill requires agencies to publish outcomes.</p>',
      text_length: 96,
      update_date: '2026-01-20T10:00:00Z',
      is_latest: true,
    },
    {
      version_code: '00',
      action_date: '2025-09-10',
      action_desc: 'Introduced in House',
      text_html: '<p>As introduced.</p>',
      text_length: 21,
      update_date: '2025-09-17T10:00:00Z',
      is_latest: false,
    },
  ],
  cosponsor_list: [
    {
      bioguide_id: 'S001213',
      name: 'Bryan Steil',
      full_name: 'Rep. Steil, Bryan [R-WI-1]',
      party: 'R',
      state: 'WI',
      district: 1,
      date: '2026-09-04',
      is_original_cosponsor: false,
      withdrawn_date: null,
      is_withdrawn: false,
      is_tracked_member: true,
    },
    {
      bioguide_id: 'K000401',
      name: 'Kevin Kiley',
      full_name: 'Rep. Kiley, Kevin [R-CA-3]',
      party: 'R',
      state: 'CA',
      district: 3,
      date: '2026-09-05',
      is_original_cosponsor: false,
      withdrawn_date: null,
      is_withdrawn: false,
      is_tracked_member: true,
    },
    {
      bioguide_id: 'X000001',
      name: 'Dana Example',
      full_name: 'Rep. Example, Dana [D-OR-4]',
      party: 'D',
      state: 'OR',
      district: 4,
      date: '2026-09-06',
      is_original_cosponsor: false,
      withdrawn_date: '2026-09-20',
      is_withdrawn: true,
      is_tracked_member: false,
    },
  ],
  actions: [
    {
      action_date: '2025-09-11',
      action_time: null,
      action_code: 'H11100',
      action_text: 'Referred to the Committee on Energy and Commerce.',
      action_type: 'IntroReferral',
      source_system: 'House floor actions',
    },
    {
      action_date: '2025-09-10',
      action_time: '14:02:00',
      action_code: 'Intro-H',
      action_text: 'Introduced in House',
      action_type: 'IntroReferral',
      source_system: 'Library of Congress',
    },
    {
      action_date: '2025-09-10',
      action_time: null,
      action_code: null,
      action_text: 'Sponsor introductory remarks on measure.',
      action_type: 'Committee',
      source_system: 'Library of Congress',
    },
  ],
  roll_calls: [
    {
      chamber: 'house',
      session: 2,
      roll_number: 295,
      voted_at: '2026-01-14T18:24:00Z',
      vote_date: '2026-01-14',
      question: 'On Passage',
      result: 'Passed',
      yea_total: 237,
      nay_total: 169,
      present_total: 1,
      not_voting_total: 26,
      tracked_positions: [
        { bioguide_id: 'S001213', name: 'Bryan Steil', party: 'Republican', position: 'Yea' },
        { bioguide_id: 'J000294', name: 'Hakeem Jeffries', party: 'Democrat', position: 'Nay' },
      ],
      source_url: 'https://clerk.house.gov/evs/2026/roll295.xml',
    },
  ],
  sources: [],
};

/** A minor bill the Congressional Research Service has not summarised. */
export const BILL_NO_SUMMARY: BillDetail = {
  ...BILL,
  bill_number: '4735',
  label: 'H.R. 4735',
  title: 'Business of Insurance Regulatory Reform Act of 2025',
  summary: null,
  summary_versions: [],
  summary_count: 0,
  has_summary: false,
  cosponsors: { total: 0, democratic: 0, republican: 0, other: 0, withdrawn: 0 },
  cosponsor_list: [],
  roll_call_count: 0,
  roll_calls: [],
  sponsor: { ...BILL.sponsor, bioguide_id: 'S001213', name: 'Bryan Steil', is_tracked: true },
};

export const AMENDMENT: BillDetail = {
  ...BILL_NO_SUMMARY,
  bill_type: 'hamdt',
  bill_number: '9',
  label: 'H.Amdt. 9',
  kind: 'amendment',
  title: 'Amendment 9 to H.R. 21',
  amended_bill_congress: 119,
  amended_bill_type: 'hr',
  amended_bill_number: '21',
};

/** GET /meta/sessions for the 119th, as mart.congress_session holds it. */
export const SESSIONS: CongressSession[] = [
  {
    congress: 119,
    session: 1,
    year: 2025,
    start_date: '2025-01-03',
    end_date: '2026-01-02',
    first_roll_call_date: '2025-01-03',
    last_roll_call_date: '2025-12-19',
    roll_calls: 1021,
    is_current: false,
  },
  {
    congress: 119,
    session: 2,
    year: 2026,
    start_date: '2026-01-03',
    end_date: '2027-01-03',
    first_roll_call_date: '2026-01-05',
    last_roll_call_date: '2026-09-10',
    roll_calls: 526,
    is_current: true,
  },
];
